ALTER TABLE registros
ADD CONSTRAINT FK_REGISTRO
FOREIGN KEY (EMPLEADOS_ID)
REFERENCES
EMPLEADOS(ID)
;

ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_EMPLEADO
FOREIGN KEY (PERSONAS_ID)
REFERENCES
PERSONAS(ID)
;